/**
 * Codegen: derived types from a PUBLISHED catalog document.
 *
 * `defineCatalog` derives key/pattern/scope unions from the catalog
 * literal — but only for code that imports the source module. Everything
 * that consumes the published `CatalogDocument` instead (federated apps
 * reading another team's catalog, tooling, services in other repos) gets
 * `string`, because a document is data, not a literal. This module is how
 * autocomplete crosses that wire: emit a `.ts` module of literal unions
 * from the document, and pin them back on with
 * `catalogFromDocument<AlfizKey, AlfizPattern, AlfizScopeId>(doc)`.
 *
 * The emitted module is deliberately dependency-free (pure type aliases),
 * so it can be committed, reviewed in diffs — a new permission shows up as
 * a one-line addition — and imported from anywhere, client bundles
 * included, without pulling in any Alfiz runtime.
 */

import type { CatalogDocument } from "@alfiz/core";

export interface CodegenOptions {
  /**
   * The identifier prefix for the emitted type aliases: `<prefix>Key`,
   * `<prefix>Pattern`, `<prefix>ScopeType`, `<prefix>ScopeId`.
   * Default `"Alfiz"`.
   */
  prefix?: string | undefined;
  /** Extra header lines (e.g. the source path or a lint-disable). */
  banner?: readonly string[] | undefined;
}

const quote = (value: string): string => JSON.stringify(value);

const unionLines = (members: readonly string[]): string =>
  members.length === 0 ? " never" : `\n  | ${members.join("\n  | ")}`;

/**
 * Renders a self-contained TypeScript module declaring the catalog's
 * derived unions. Deterministic for a given document (members are sorted),
 * so regeneration diffs are exactly the catalog change.
 */
export function generateCatalogTypes(
  document: CatalogDocument,
  options: CodegenOptions = {},
): string {
  const prefix = options.prefix ?? "Alfiz";
  const keys = [...document.leaves.map((l) => l.key)].sort();
  const groupWildcards = [...document.groups.map((g) => `${g.path}.*`)].sort();
  const scopeTypes = [...document.scopeTypes.map((s) => s.type)].sort();

  const lines: string[] = [
    `// Generated by \`alfiz-verify codegen\` from catalog ${quote(document.namespace)} (formatVersion ${document.formatVersion}).`,
    `// Do not edit by hand — regenerate when the published catalog changes.`,
    ...(options.banner ?? []),
    ``,
    `/** Every concrete permission key of the published catalog. */`,
    `export type ${prefix}Key =${unionLines(keys.map(quote))};`,
    ``,
    `/** Every valid pattern: keys, group wildcards, and the bare \`*\`. */`,
    `export type ${prefix}Pattern =`,
    `  | "*"`,
    `  | ${prefix}Key${groupWildcards.length > 0 ? `\n  | ${groupWildcards.map(quote).join("\n  | ")}` : ""};`,
    ``,
    `/** The declared scope types. */`,
    `export type ${prefix}ScopeType =${unionLines(scopeTypes.map(quote))};`,
    ``,
    `/** Scope instance ids: \`*\` or \`<scopeType>:<instanceId>\`. */`,
    `export type ${prefix}ScopeId =${
      scopeTypes.length === 0
        ? ` "*";`
        : ` "*" | \`\${${prefix}ScopeType}:\${string}\`;`
    }`,
    ``,
  ];
  return lines.join("\n");
}
